TRUNCATE TABLE "Species", "Nurseries", "InventorySellers" RESTART IDENTITY;

INSERT INTO "Species" ("Name", "CommonName", "Info", "MinHeight", "MaxHeight", "Clumping", "MinZone", "MaxZone", "MinLight", "MaxLight") VALUES ('Phyllostachys Nigra', 'Black Bamboo', 'The exquisite black canes and ability to tolerate temperatures down to 0F make Black bamboo one of the most sought after bamboo species. As a running running species, it requires an in-ground barrier or large container to keep from becoming invasive, but most owners agree that it is well worth the initial hassle. Given time and proper containment, it can form a dense privacy screen, or be used as an ornamental or accent plant.', 15, 25, False, 7, 10, 2, 4);
INSERT INTO "Species" ("Name", "CommonName", "Info", "MinHeight", "MaxHeight", "Clumping", "MinZone", "MaxZone", "MinLight", "MaxLight") VALUES ('Dendrocalamus minor Amoenus', 'Ghost Bamboo', 'Ghost Bamboo, also known as Angel Mist Bamboo and Angel Mist Ghost Bamboo, is the smallest and most cold-hardy of the giant bamboos, the greatest point of interest is the culms that emerge with a blueish white powder that eventually ages into a golden yellow with dark green striping. The mature plant does not have any lower branches, both keeping its intriguing culms on full display and pests at bay. This growth habit, combined with its large, tropical leaves, allow it to provide shade and privacy.', 30, 40, True, 9, 11, 2, 4);
INSERT INTO "Species" ("Name", "CommonName", "Info", "MinHeight", "MaxHeight", "Clumping", "MinZone", "MaxZone", "MinLight", "MaxLight") VALUES ('Bambusa multiplex Alphonse Karr', 'Alphonse Karr Bamboo', 'Alphonse Karr Bamboo is a handsome yellow bamboo that is easy to care for. Once established, it is drought tolerant and can survive high winds, salt spray, and a range of soil pH. When contained and given little water or fertilizer, it can reach 25 feet, but when given space, fertilizer, and water, it can exceed 40 feet. Its green-striped gold canes against its green leaves can make it a strikingly colorful choice for a privacy screen.', 20, 40, True, 8, 10, 2, 4);


INSERT INTO "Nurseries" ("Name", "Shipping", "PhoneNumber", "Email", "StreetAddress", "City", "State", "Zipcode", "Description", "Website") VALUES ('Lewis Bamboo', true, '877-796-2263', 'info@lewisbamboo.com', '121 Creekview Road', 'Oakman', 'AL', '35579', 'A decent nursery I guess', 'https://www.lewisbamboo.com');
INSERT INTO "Nurseries" ("Name", "Shipping", "PhoneNumber", "Email", "StreetAddress", "City", "State", "Zipcode", "Description", "Website") VALUES ('Bamboo Plants Online', true, '888-784-7336', 'kenny@bambooplantsonline.com', '23370 Dixie Rd', 'Labelle', 'FL', '33935', 'We are a 20 acre bamboo nursery in southwest Florida. We have a large inventory of non-invasive clumping bamboos in 1 & 3 gallon sizes for easy transportation and shipping. Come visit our nursery or order online. We use 1-2 day UPS Ground to ship throughout the lower 48 states.', 'https://www.bambooplantsonline.com');
INSERT INTO "Nurseries" ("Name", "Shipping", "PhoneNumber", "Email", "StreetAddress", "City", "State", "Zipcode", "Description", "Website") VALUES ('Wilson Bros Gardens', true, '770-573-1778', 'team@wilsonbrosgardens.com','1759 McGarity Rd', 'McDonough', 'GA', '770-573-1778', 'Very pricey but great selection', 'https://www.wilsonbrosgardens.com');


INSERT INTO "InventorySellers" ("SpeciesId", "NurseryId") VALUES (1, 1);
INSERT INTO "InventorySellers" ("SpeciesId", "NurseryId") VALUES (1, 3);
INSERT INTO "InventorySellers" ("SpeciesId", "NurseryId") VALUES (2, 2);
INSERT INTO "InventorySellers" ("SpeciesId", "NurseryId") VALUES (3, 1);
INSERT INTO "InventorySellers" ("SpeciesId", "NurseryId") VALUES (3, 2);
INSERT INTO "InventorySellers" ("SpeciesId", "NurseryId") VALUES (3, 3);